# Generated by Django 4.1 on 2022-08-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
